### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jo16oh** [obaland/vfiler-fzf#2] opened 2024-03-15 12:27 UTC
Hello and first of all, thank you for the awesome plugin! Vfiler is ideal file explorer for me.

I got error messages below when I tried to install vfiler-fzf plugin following the instruction on README, 
Is my setup incorrect? Or the plugin no longer maintained?

```
Failed to run `config` for vfiler.vim

...local/share/nvim/lazy/vfiler-fzf/lua/vfiler/fzf/sink.lua:1: module 'vfiler/actions/api' not found:
^Ino field package.preload['vfiler/actions/api']
cache_loader: module vfiler/actions/api not found
cache_loader_lib: module vfiler/actions/api not found
^Ino file './vfiler/actions/api.lua'
^Ino file '/opt/homebrew/share/luajit-2.1/vfiler/actions/api.lua'
^Ino file '/usr/local/share/lua/5.1/vfiler/actions/api.lua'
^Ino file '/usr/local/share/lua/5.1/vfiler/actions/api/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/vfiler/actions/api.lua'
^Ino file '/opt/homebrew/share/lua/5.1/vfiler/actions/api/init.lua'
^Ino file './vfiler/actions/api.so'
^Ino file '/usr/local/lib/lua/5.1/vfiler/actions/api.so'
^Ino file '/opt/homebrew/lib/lua/5.1/vfiler/actions/api.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /vfiler-fzf/lua/vfiler/fzf/sink.lua:1
  - /vfiler-fzf/lua/vfiler/fzf/config.lua:2
  - /vfiler-fzf/lua/vfiler/fzf/action.lua:2
  - nvim/lua/plugins/vfiler.lua:7 _in_ **config**
  - nvim/lua/lazy-startup.lua:14
  - nvim/init.lua:9
25 more lines
25 fewer lines; before #505  4 seconds ago
```

My lazy.nvim setup ↓
```lua
return {
  "obaland/vfiler.vim",
  dependencies = { "obaland/vfiler-column-devicons", "junegunn/fzf", "junegunn/fzf.vim", "obaland/vfiler-fzf" },
  build = function() vim.fn['fzf#install']() end,
  config = function()
    local action = require('vfiler/action')
    local fzf_action = require('vfiler/fzf/action')
    require('vfiler/config').setup {
      options = {
        columns = 'indent,devicons,name,mode,size,time',
        layout = 'floating',
        find_file = true,
        listed = false,
        preview = {
          layout = 'floating',
        },
        zindex = 1,
      },

      mappings = {
      }
    }
  end
}
```

OS: macOS 14.3.1
Neovim version: v0.9.5

Thank you for taking the time!

**Comment by obaland** [comment] 2024-03-15 15:23
@jo16oh 
Thank you for contacting.
Its an honor to have you use `vfiler.vim`.
Now, `vfiler-fzf`, I have neglected to maintain it for a while. Sorry about that.

It will be fixed after investigating the cause.
I apologize for the inconvenience, but please give me a little time.

**Comment by obaland** [comment] 2024-03-17 01:38
@jo16oh 
I've made the corrections. Please take a moment to check them. (aeecaffbbfbc91e3643bbdd9bc6dfb2f0813de3e)
Also, `vfiler.vim` should be up-to-date. ([355ad69](https://github.com/obaland/vfiler.vim/commit/355ad692e4d94020f6dcda0d59e9dbdbd9eaaa56))

The current version of vfiler-fzf is quite basic. If you have any requests or ideas, I would be really happy to hear from you. I’m always open to considering new suggestions with a positive attitude.

Thank you so much for your continued support.

**Comment by jo16oh** [comment] 2024-03-17 09:56
I've updated the plugin and it works perfectly in my environment!
I really appreciate for your quick correction👏

**Closed as completed** 2024-03-17 23:54 UTC
Labels: bug
